### ISSUE TITLE
Create Todo Page

### ISSUE THREAD

**Issue by liwoo** [liwoo/flutter-firebase-bloc-starter#4]
The Todo Screen will have 

- [ ] A [Reorderable ListView](https://api.flutter.dev/flutter/material/ReorderableListView-class.html) of todos to be fetched from a Todo BLoC
- [ ] Floating Action Button to open a modal where a new Todo can be Added 
- [ ] Todo's can be checked and a BLoC event fired
- [ ] The Todo's must be saved in Firebase through a Todo Repository
- [ ] Todo's can be Reordered
- [ ] Todo's can be edited by opening another modal and firing an event that calls a `editTodo()` repository method through the bloc
- [ ] Add an integration test for adding a new todo
- [ ] Add an integration of checking off a todo
- [ ] Add integration test of editing a todo
